# Homework 3  - Tryout pandas and numpy

Copy this notebook. Rename it as: YOURNAME-Homework-panda-numpy-Sept-2017

with your name replacing yourname and  replaced with the date you submit or to the last part.

Do the homeworks problems below.

Upload your completed jupyter notebook to your github site and send me the url via the elearning site as your homework submission. Please note that you need to do your own 3.4, and 3.5 if you share data and analysis from others then you cannot get more than a 3.  

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [4]:
import pandas as pd
import numpy as np

mydata = pd.read_csv("./data/ccp_current_csv.csv")
mydata


STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW              Madison St (N)   
15         Underwood Pl       NW            North Capitol St   
16              20th St       NW                 Columbia Rd   
17          Quintana Pl       NE                      3rd St   
18         Tuckerman St       NE                  Kansas Ave   
19              Eads St       NE                     45th St   
20               4th St       SE                  Newcomb St   
21              Belt Rd       NW                  Jenifer St   
22            Oneida St       NE           New Hampshire Ave   
23      Carrollsburg Pl       SW                        O St   
24              23rd St       NW          Washington Cir (N)   
25           Kanawha St       NW                    Utah Ave   
26      Piney Branch Rd       NW                Underwood St   
27              30th St       NW               Stephenson Pl   
28              32nd St       NW                 Woodland Dr   
29              33rd St       NW            Broad Branch Ter   
..                  ...      ...                         ...   
435      New Jersey Ave       NW                        F St   
436             15th St       NE                     Ames Pl   
437     East Capitol St       BN                        C St   
438         Randolph St       NE                     25th Pl   
439    South Dakota Ave       NE                Delafield St   
440          Wheeler Rd       SE                 Congress St   
441      New Jersey Ave       NW                        H St   
442     Mount Olivet Rd       NE               Brentwood Pky   
443              Oak St       NW                     16th St   
444        Michigan Ave       NE                     14th St   
445                C St       NE                     20th St   
446        Virginia Ave       SE                  6th St (S)   
447              Oak St       NW                Brown St (N)   
448         Florida Ave       NE                New York Ave   
449  North Carolina Ave       NE         East Capitol St (E)   
450            Elder St       NW                      8th St   
451          Benning Rd       SE                        G St   
452           School St       SW                      4th St   
453             18th St       NW                        M St   
454       Longfellow St       NW                     16th St   
455             10th St       NW                        M St   
456          Woodley Rd       NW             Connecticut Ave   
457          Woodley Rd       NW           Cathedral Ave (E)   
458              3rd St       SW            Independence Ave   
459             16th St       NW                 Primrose Rd   
460          Woodley Rd       NW                  Woodley Pl   
461         Western Ave       NW         Chevy Chase Cir (E)   
462             49th St       NW                   Fulton St   
463       Quackenbos St       NE           New Hampshire Ave   
464    North Capitol St       BN  Hawaii Ave  Rock Creek Chu   

                 TOINTERSECTION  NOOFBLOCKS     

### 3.1.a  what is its shape and what does that mean?

In [2]:
shape = mydata.shape
print(shape)
print(type(shape))

(465, 27)
<type 'tuple'>


## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [3]:
# to return the length
print(len(mydata.index))

#to return count 'of number of rows' in each Quadrant
mydata['QUADRANT'].value_counts() 

 

465


NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [29]:
a = np.array([1,2,3,4],dtype=float)
b = np.array([5,6,7,8],dtype=float)

# addition operation
print (a+b) 

# addition functional
print (np.add(a,b)) 

[ 6.  8. 10. 12.]
[ 6.  8. 10. 12.]


### 3.3.2 subtraction a-b

In [5]:
# subtraction operation
print (a-b) 

# subtraction functional
print (np.subtract(a,b)) 

[-4. -4. -4. -4.]
[-4. -4. -4. -4.]


### 3.3.3 multiplication a*b

In [6]:
# multiplication operation
print (a*b) 

# multiplication functional
print (np.multiply(a,b)) 

[ 5. 12. 21. 32.]
[ 5. 12. 21. 32.]


### 3.3.4 divsion a/b

In [7]:
# division operation
print (a/b) 

# division functional
print (np.divide(a,b)) 

[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


### 3.3.5 modulo  a%b

In [8]:
# modulo operation
print (a%b) 

# modulo functional
print (np.mod(a,b)) 

[1. 2. 3. 4.]
[1. 2. 3. 4.]


### 3.3.6 power  a^b

In [9]:
# power operation
print (a**b) 

# power functional
print (np.power(a,b)) 

[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


### 3.3.7 Other Math functions

**Square root**

In [31]:
# squareroot operation
print(np.sqrt(a))
print(np.sqrt(b))

[1.         1.41421356 1.73205081 2.        ]
[2.23606798 2.44948974 2.64575131 2.82842712]


**Absolute value**

In [34]:
# absolute function
print np.absolute(a)
print np.absolute(b)

[1. 2. 3. 4.]


**Statistics**

In [60]:
print a.mean()
## or print np.mean(a)

print np.median(a)

print a.std()

2.5
2.5
1.118033988749895


**Cross Product**

The cross product or vector product is a binary operation on two vectors in three-dimensional space. 

The result is a vector which is perpendicular to the vectors being multiplied and normal to the plane containing them. 

The cross product of two vectors a and b is denoted by x × y

In [39]:
# cross product
x = np.array([0,0,1])
y = np.array([0,1,0])
print np.cross(x,y)
print np.cross(y,x)

[-1  0  0]
[1 0 0]


**Scalar Operations**

In [43]:
print b + 1
print 2**a

[6. 7. 8. 9.]
[ 2.  4.  8. 16.]


**Array comparisions**

In [45]:
i = np.array([1, 2, 3, 4])
j = np.array([4, 2, 2, 4])
print i == j

print i > j

[False  True False  True]
[False False  True False]


In [54]:
k = np.zeros((100, 100))
print np.any(k != 0)
print np.all(a == a)

False
True


**Logical Operations**

In [52]:
m = np.array([1, 1, 0, 0], dtype=bool)
n = np.array([1, 0, 1, 0], dtype=bool)
print np.logical_or(m, n)
print np.logical_and(m, n)
print np.all([True, True, False])
print np.any([True, True, False])

[ True  True  True False]
[ True False False False]
False
True


**Transcendental functions**

In [61]:
t = np.arange(4)
print np.sin(t)
print np.cos(t)
print np.tan(t)
print np.log(t)
print np.exp(t)

[0.         0.84147098 0.90929743 0.14112001]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]
[ 0.          1.55740772 -2.18503986 -0.14254654]
[      -inf 0.         0.69314718 1.09861229]
[ 1.          2.71828183  7.3890561  20.08553692]


/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


**Basic Reductions**

In [69]:
r = np.array([1, 2, 3, 4, 5])
# to return the sum of all elements
print r.sum()
# or print np.add.reduce(r)

# to return the product of all elements
print np.multiply.reduce(r)

# to return the minimum value of all elements
print r.min()

# to return the maximum value of all elements
print r.max()

# to return the index of the minimum value of all elements
print r.argmin()

# to return the index of the maximum value of all elements
print r.argmax()

15
120
1
5
0
4


**Boolean Indexing**

In [70]:
q = np.array([23,60,1976,100,89])
print(q == 100)
print(q > 50)

[False False False  True False]
[False  True  True  True  True]


**References**

http://www.scipy-lectures.org/intro/numpy/operations.html

https://www.tutorialspoint.com/numpy/numpy_array_from_numerical_ranges.htm

https://www.python-course.eu/matrix_arithmetic.php

## Homework 3.4
Find your own data and load it into a dataframe

One of IBM sample data sets of a telephone company, from www.kaggle.com

In [5]:
# To predict behavior to retain customers, analyze all relevant customer data 
# and develop focused customer retention programs.
my_telco_data = pd.read_csv("./data/WA_Fn-UseC_-Telco-Customer-Churn.csv")

# to visualize the first few rows on our DataFrame, the default value is 5.
my_telco_data.head()

# df.tail(n=5), to return the last 5 rows on our DataFrame

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ...  DeviceProtection  \
0  No phone service             DSL             No  ...                No   
1                No             DSL            Yes  ...               Yes   
2                No             DSL            Yes  ...                No   
3  No phone service             DSL            Yes  ...               Yes   
4                No     Fiber optic             No  ...                No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [18]:
# to return the column names
my_telco_data.columns

Index([u'customerID', u'gender', u'SeniorCitizen', u'Partner', u'Dependents',
       u'tenure', u'PhoneService', u'MultipleLines', u'InternetService',
       u'OnlineSecurity', u'OnlineBackup', u'DeviceProtection', u'TechSupport',
       u'StreamingTV', u'StreamingMovies', u'Contract', u'PaperlessBilling',
       u'PaymentMethod', u'MonthlyCharges', u'TotalCharges', u'Churn'],
      dtype='object')

In [19]:
# to return a quick statistic summary of data, only the numeric columns
my_telco_data.describe()

SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

### 3.5.1 Selecting Data

In [23]:
# to return the first 5 data values from column 'customerID'
my_telco_data.customerID.head()

# or
# my_telco_data['customerID'].head()

0    7590-VHVEG
1    5575-GNVDE
2    3668-QPYBK
3    7795-CFOCW
4    9237-HQITU
Name: customerID, dtype: object

In [25]:
# Slicing the rows using '[]' to select the data
my_telco_data[0:2]

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   

      MultipleLines InternetService OnlineSecurity  ...  DeviceProtection  \
0  No phone service             DSL             No  ...                No   
1                No             DSL            Yes  ...               Yes   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   

      PaymentMethod MonthlyCharges  TotalCharges Churn  
0  Electronic check          29.85         29.85    No  
1      Mailed check          56.95        1889.5    No  

[2 rows x 21 columns]

In [30]:
# to return a particular value from a row, use 'at'
my_telco_data.at[1,'customerID']

'5575-GNVDE'

**Selecting using 'loc' property**

loc property takes two arguments, 

-  The first is the indexes of the slices, none defined here indicates that there isn’t any row slicing
-  The second is the name(s) of the columns we desire to slice.

In [27]:
# to return data on selected columns 
my_telco_data.loc[:,['customerID','PaymentMethod','TotalCharges']].head(10)

customerID              PaymentMethod TotalCharges
0  7590-VHVEG           Electronic check        29.85
1  5575-GNVDE               Mailed check       1889.5
2  3668-QPYBK               Mailed check       108.15
3  7795-CFOCW  Bank transfer (automatic)      1840.75
4  9237-HQITU           Electronic check       151.65
5  9305-CDSKC           Electronic check        820.5
6  1452-KIOVK    Credit card (automatic)       1949.4
7  6713-OKOMC               Mailed check        301.9
8  7892-POOKP           Electronic check      3046.05
9  6388-TABGU  Bank transfer (automatic)      3487.95

In [29]:
# to return required data by selecting the columns and slicing the rows
my_telco_data.loc[0:7,['customerID','PaymentMethod','TotalCharges']]

customerID              PaymentMethod TotalCharges
0  7590-VHVEG           Electronic check        29.85
1  5575-GNVDE               Mailed check       1889.5
2  3668-QPYBK               Mailed check       108.15
3  7795-CFOCW  Bank transfer (automatic)      1840.75
4  9237-HQITU           Electronic check       151.65
5  9305-CDSKC           Electronic check        820.5
6  1452-KIOVK    Credit card (automatic)       1949.4
7  6713-OKOMC               Mailed check        301.9

In [43]:
# selecting multiple columns and rows
my_telco_data.loc[1156:1158,['customerID','PhoneService','InternetService']]

customerID PhoneService InternetService
1156  0621-CXBKL          Yes              No
1157  5268-DSMNQ          Yes     Fiber optic
1158  5334-JLAXU          Yes     Fiber optic

### 3.5.2 Booloean Indexing

As Panda supports Boolean indexing, it is possible to filter out data from a dataframe based on the value of a column

In [32]:
# to return the data of all senior citizens
my_telco_data[my_telco_data.SeniorCitizen == 1]

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
20    8779-QRDMV    Male              1      No         No       1   
30    3841-NFECX  Female              1     Yes         No      71   
31    4929-XIHVW    Male              1     Yes         No       2   
34    3413-BMNZE    Male              1      No         No       1   
50    8012-SOUDQ  Female              1      No         No      43   
52    6575-SUVOI  Female              1     Yes         No      25   
53    7495-OOKFY  Female              1     Yes         No       8   
54    4667-QONEA  Female              1     Yes        Yes      60   
55    1658-BYGOY    Male              1      No         No      18   
57    5067-XJQFU    Male              1     Yes        Yes      66   
72    1891-QRQSA    Male              1     Yes        Yes      64   
75    2673-CXQEU  Female              1      No         No      56   
78    0191-ZHSKZ    Male              1      No         No      30   
91    2424-WVHPL    Male              1      No         No       1   
99    4598-XLKNJ  Female              1     Yes         No      25   
103   5386-THSLQ  Female              1     Yes         No      66   
113   4846-WHAFZ  Female              1     Yes         No      37   
126   4412-YLTKF  Female              1      No         No      27   
129   2639-UGMAZ    Male              1      No         No      71   
139   0390-DCFDQ  Female              1     Yes         No       1   
140   3146-MSEGF  Female              1     Yes        Yes      72   
144   1131-QQZEB    Male              1     Yes         No      71   
168   3445-HXXGF    Male              1     Yes         No      58   
176   2656-FMOKZ  Female              1      No         No      15   
177   2070-FNEXE  Female              1      No         No       7   
214   2504-DSHIH    Male              1     Yes         No      23   
238   0094-OIFMO  Female              1      No         No      11   
243   9058-HRZSV  Female              1     Yes         No      65   
244   4522-AKYLR  Female              1      No         No      13   
245   0221-WMXNQ    Male              1      No         No       4   
...          ...     ...            ...     ...        ...     ...   
6882  8065-QBYTO  Female              1      No         No      71   
6886  7234-FECYN  Female              1      No         No       8   
6894  1400-MMYXY    Male              1     Yes         No       3   
6900  7921-LMDFQ    Male              1      No         No      51   
6902  5820-PTRYM  Female              1     Yes         No      56   
6904  6211-WHMYA  Female              1      No         No      64   
6914  7142-HVGBG    Male              1     Yes         No      43   
6942  3454-JFUBC    Male              1      No         No      68   
6953  1564-NTYXF  Female              1      No         No      13   
6956  2451-YMUXS    Male              1      No         No      67   
6960  4690-PKDQG  Female              1     Yes         No      42   
6962  0886-QGENL  Female              1     Yes         No      27   
6965  7789-CRUVC  Female              1     Yes         No      61   
6967  8739-WWKDU    Male              1      No         No      25   
6968  8685-WHQPW  Female              1      No         No      22   
6971  7240-FQLHE  Female              1     Yes         No      18   
6972  6664-FPDAC  Female              1      No         No      56   
6973  9972-VAFJJ  Female              1     Yes         No      53   
6980  0786-VSSUD    Male              1      No         No      16   
6987  5981-ZVXOT  Female              1      No         No      35   
6993  6583-QGCSI  Female              1     Yes         No      50   
7007  2274-XUATA    Male              1     Yes         No      72   
7008  1980-KXVPM  Female              1      No         No       3   
7010  0723-DRCLG  Female              1     Yes         No       1   
7015  0666-UXTJO    Male              1     Yes         No      34   
7023  1035-IPQPU

In [35]:
# to return values filtering on multiple values, using the builtin function df.isin()
my_telco_data[my_telco_data['PaymentMethod'].isin(['Mailed check','Electronic check'])]

# my_telco_data[my_telco_data['Contract'].isin(['One year','Two year'])]


customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
4     9237-HQITU  Female              0      No         No       2   
5     9305-CDSKC  Female              0      No         No       8   
7     6713-OKOMC  Female              0      No         No      10   
8     7892-POOKP  Female              0     Yes         No      28   
10    9763-GRSKD    Male              0     Yes        Yes      13   
14    5129-JLPIS    Male              0      No         No      25   
16    8191-XWSZG  Female              0      No         No      52   
19    4183-MYFRB  Female              0      No         No      21   
20    8779-QRDMV    Male              1      No         No       1   
22    1066-JKSGK    Male              0      No         No       1   
26    6467-CHFZW    Male              0     Yes        Yes      47   
27    8665-UTDHZ    Male              0     Yes        Yes       1   
29    8773-HHUOZ  Female              0      No        Yes      17   
32    6827-IEAUQ  Female              0     Yes        Yes      27   
36    6047-YHPVI    Male              0      No         No       5   
38    5380-WJKOV    Male              0      No         No      34   
40    8865-TNMNX    Male              0     Yes        Yes      10   
42    9867-JCZSP  Female              0     Yes        Yes      17   
44    4080-IIARD  Female              0     Yes         No      13   
45    3714-NTNFO  Female              0      No         No      49   
46    5948-UJZLF    Male              0      No         No       2   
47    7760-OYPDY  Female              0      No         No       2   
50    8012-SOUDQ  Female              1      No         No      43   
55    1658-BYGOY    Male              1      No         No      18   
57    5067-XJQFU    Male              1     Yes        Yes      66   
60    0434-CSFON  Female              0     Yes         No      47   
64    5698-BQJOH  Female              0      No         No       9   
...          ...     ...            ...     ...        ...     ...   
6987  5981-ZVXOT  Female              1      No         No      35   
6990  0376-OIWME    Male              0     Yes         No      36   
6993  6583-QGCSI  Female              1     Yes         No      50   
6995  7164-BPTUT    Male              0      No        Yes      57   
6997  2523-EWWZL  Female              0     Yes         No      27   
6998  0928-XUTSN  Female              0      No         No      13   
6999  2108-XWMPY    Male              0      No         No       3   
7000  0052-YNYOT  Female              0      No         No      67   
7001  6304-IJFSQ    Male              0      No         No       3   
7003  4501-VCPFK    Male              0      No         No      26   
7009  7703-ZEKEF    Male              0      No         No      23   
7010  0723-DRCLG  Female              1     Yes         No       1   
7011  5482-NUPNA  Female              0      No         No       4   
7012  6691-CCIHA  Female              0     Yes         No      62   
7014  9053-EJUNL    Male              0      No         No      41   
7016  1471-GIQKQ  Female              0      No         No       1   
7018  1122-JWTJW    Male              0     Yes        Yes       1   
7019  9710-NJERN  Female              0      No         No      39   
7020  9837-FWLCH    Male              0     Yes        Yes      12   
7021  1699-HPSBG    Male              0      No         No      12   
7022  7203-OYKCT    Male              0      No         No      72   
7023  1035-IPQPU  Female              1     Yes         No      63   
7027  0550-DCXLH    Male              0      No         No      13   
7029  2235-DWLJU  Female              1      No         No       6   
7030  0871-OPBXW  Female              0      No         No       2   
7032  6894-LFHLY

### 3.5.3 Column operations

**Derving a new column from existing**

New columns can be derived from an existing dataset to count, compare values and help analyze the data

In [36]:
# to return the count against a column value
my_telco_data['PaymentMethod'].value_counts()

Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: PaymentMethod, dtype: int64

**Creating a new column**

Creating a column is much like creating a new key-value pair in a dictionary. 
By assigning values to the new column name, you add a column to the DataFrame

New column(s) created will be added to the end of the column set(extreme right).

In [44]:
# creating new column
my_telco_data['new_column'] = "Unknown Value"
my_telco_data.loc[0:3,['customerID','new_column']]

customerID     new_column
0  7590-VHVEG  Unknown Value
1  5575-GNVDE  Unknown Value
2  3668-QPYBK  Unknown Value
3  7795-CFOCW  Unknown Value

**Replacing values in a column**

In [53]:
# to rename a column, .replace property is used
my_telco_data.replace("Unknown Value", np.nan).head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity    ...     TechSupport  \
0  No phone service             DSL             No    ...              No   
1                No             DSL            Yes    ...              No   
2                No             DSL            Yes    ...              No   
3  No phone service             DSL            Yes    ...             Yes   
4                No     Fiber optic             No    ...              No   

  StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No              No  Month-to-month              Yes   
1          No              No        One year               No   
2          No              No  Month-to-month              Yes   
3          No              No        One year               No   
4          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges TotalCharges  Churn new_column  
0           Electronic check          29.85        29.85     No        NaN  
1               Mailed check          56.95       1889.5     No        NaN  
2               Mailed check          53.85       108.15    Yes        NaN  
3  Bank transfer (automatic)          42.30      1840.75     No        NaN  
4           Electronic check          70.70       151.65    Yes        NaN  

[5 rows x 22 columns]

**Renaming a Column**

In [58]:
# to rename a column, .rename property is used
my_telco_data.rename(columns ={"new_column": "dummy_column"}, inplace=True)
my_telco_data.loc[0:3,['customerID','dummy_column']]

customerID   dummy_column
0  7590-VHVEG  Unknown Value
1  5575-GNVDE  Unknown Value
2  3668-QPYBK  Unknown Value
3  7795-CFOCW  Unknown Value

In [61]:
# to return sample data
my_telco_data.sample(n=4)

customerID gender  SeniorCitizen Partner Dependents  tenure  \
5638  5143-WMWOG   Male              0      No         No       1   
3166  9097-ZUBYC   Male              0     Yes         No      14   
3493  5968-VXZLG   Male              0      No         No       2   
5939  4712-AUQZO   Male              0      No         No      18   

     PhoneService     MultipleLines InternetService       OnlineSecurity  \
5638          Yes                No              No  No internet service   
3166          Yes                No             DSL                   No   
3493          Yes                No             DSL                   No   
5939           No  No phone service             DSL                  Yes   

          ...                TechSupport          StreamingTV  \
5638      ...        No internet service  No internet service   
3166      ...                        Yes                   No   
3493      ...                         No                   No   
5939      ...                         No                   No   

          StreamingMovies        Contract PaperlessBilling  \
5638  No internet service  Month-to-month               No   
3166                   No  Month-to-month               No   
3493                   No  Month-to-month              Yes   
5939                   No  Month-to-month               No   

                  PaymentMethod MonthlyCharges TotalCharges  Churn  \
5638           Electronic check          19.95        19.95    Yes   
3166  Bank transfer (automatic)          48.80        664.4     No   
3493  Bank transfer (automatic)          46.60         87.9     No   
5939               Mailed check          33.60       550.35     No   

       dummy_column  
5638  Unknown Value  
3166  Unknown Value  
3493  Unknown Value  
5939  Unknown Value  

[4 rows x 22 columns]

In [62]:
# to return the sorted dataframe in the defined order
my_telco_data.sort_values(by='customerID', ascending=False)[0:5]

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
1634  9995-HOTOH    Male              0     Yes        Yes      63   
1996  9993-LHIEB    Male              0     Yes        Yes      67   
1260  9992-UJOEL    Male              0      No         No       2   
2875  9992-RRAMN    Male              0     Yes         No      22   
3607  9987-LUTYD  Female              0      No         No      13   

     PhoneService     MultipleLines InternetService OnlineSecurity  \
1634           No  No phone service             DSL            Yes   
1996          Yes                No             DSL            Yes   
1260          Yes                No             DSL             No   
2875          Yes               Yes     Fiber optic             No   
3607          Yes                No             DSL            Yes   

          ...       TechSupport StreamingTV StreamingMovies        Contract  \
1634      ...                No         Yes             Yes        Two year   
1996      ...               Yes          No             Yes        Two year   
1260      ...                No          No              No  Month-to-month   
2875      ...                No          No             Yes  Month-to-month   
3607      ...               Yes          No              No        One year   

     PaperlessBilling     PaymentMethod MonthlyCharges TotalCharges  Churn  \
1634               No  Electronic check          59.00       3707.6     No   
1996               No      Mailed check          67.85      4627.65     No   
1260              Yes      Mailed check          50.30        92.75     No   
2875              Yes  Electronic check          85.10       1873.7    Yes   
3607               No      Mailed check          55.15        742.9     No   

       dummy_column  
1634  Unknown Value  
1996  Unknown Value  
1260  Unknown Value  
2875  Unknown Value  
3607  Unknown Value  

[5 rows x 22 columns]

### 3.5.5 Summary functions

In [63]:
# to return - number of rows in the dataset
my_telco_data['customerID'].count()

7043

In [65]:
# to return - maximum 'tenure' 
my_telco_data['tenure'].max()

72

In [67]:
# to return - the total sum of monthly payment done through mailed check
my_telco_data['MonthlyCharges'][my_telco_data['PaymentMethod'] == 'Mailed check'].sum()

70794.3

In [68]:
# to return - the count on Internet services
my_telco_data['InternetService'].value_counts()

Fiber optic    3096
DSL            2421
No             1526
Name: InternetService, dtype: int64

In [69]:
# to return - Number of non-null unique Contract entries
my_telco_data['Contract'].nunique()

3

### 3.5.6 Groupby : Split, Apply and Combine 
    
Any groupby operation involves one of the following operations on the original object,

-  Splitting the Object

-  Applying a function

-  Combining the results

In the apply functionality, we can perform the following operations,

-  Aggregation − computing a summary statistic

-  Transformation − perform some group-specific operation

-  Filtration − discarding the data with some condition

**Step 1:** split the data into groups by creating a groupby object from the original DataFrame

In [8]:
# Group by column 'Contract'
my_telco_data_by_contract = my_telco_data.groupby('Contract')

# check type of groupby object 
type(my_telco_data_by_contract)

pandas.core.groupby.groupby.DataFrameGroupBy

**Step 2:** apply 'describe' function

In [9]:
my_telco_data_by_contract.describe().head()

MonthlyCharges                                              \
                        count       mean        std    min     25%    50%   
Contract                                                                    
Month-to-month         3875.0  66.398490  26.926599  18.75  45.850  73.25   
One year               1473.0  65.048608  31.840539  18.25  26.900  68.75   
Two year               1695.0  60.770413  34.678865  18.40  24.025  64.35   

                               SeniorCitizen            ...             \
                   75%     max         count      mean  ...   75%  max   
Contract                                                ...              
Month-to-month  88.875  117.45        3875.0  0.208258  ...   0.0  1.0   
One year        94.800  118.60        1473.0  0.128988  ...   0.0  1.0   
Two year        90.450  118.75        1695.0  0.085546  ...   0.0  1.0   

                tenure                                                     
                 count       mean        std  min   25%   50%   75%   max  
Contract                                                                   
Month-to-month  3875.0  18.036645  17.689054  1.0   3.0  12.0  29.0  72.0  
One year        1473.0  42.044807  19.035883  0.0  27.0  44.0  58.0  72.0  
Two year        1695.0  56.735103  18.209363  0.0  48.0  64.0  71.0  72.0  

[3 rows x 24 columns]

**Step 3:** combine the results into a new DataFrame.

In [12]:
my_telco_data_by_contract_median = my_telco_data_by_contract.median()
my_telco_data_by_contract_median.head()

SeniorCitizen  tenure  MonthlyCharges
Contract                                             
Month-to-month              0      12           73.25
One year                    0      44           68.75
Two year                    0      64           64.35

**Selecting a single group**

get_group() method is used to select a single group.

In [13]:
grouped = my_telco_data.groupby('PaymentMethod')
print grouped.get_group('Electronic check')

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
4     9237-HQITU  Female              0      No         No       2   
5     9305-CDSKC  Female              0      No         No       8   
8     7892-POOKP  Female              0     Yes         No      28   
14    5129-JLPIS    Male              0      No         No      25   
19    4183-MYFRB  Female              0      No         No      21   
20    8779-QRDMV    Male              1      No         No       1   
26    6467-CHFZW    Male              0     Yes        Yes      47   
27    8665-UTDHZ    Male              0     Yes        Yes       1   
36    6047-YHPVI    Male              0      No         No       5   
38    5380-WJKOV    Male              0      No         No      34   
44    4080-IIARD  Female              0     Yes         No      13   
45    3714-NTNFO  Female              0      No         No      49   
47    7760-OYPDY  Fe

**Aggregations**

An aggregated function returns a single aggregated value for each group. Once the group by object is created, several aggregation operations can be performed on the grouped data using 'agg()' method.


In [15]:
# to return the mean of the 'tenure' grouped by 'Internet Service'
grouped = my_telco_data.groupby('InternetService')
print grouped['tenure'].agg(np.mean)

InternetService
DSL            32.821561
Fiber optic    32.917959
No             30.547182
Name: tenure, dtype: float64


In [17]:
# to return the size of the 'tenure' grouped by 'Internet Service'
grouped = my_telco_data.groupby('InternetService')
print grouped['tenure'].agg(np.size)

InternetService
DSL            2421
Fiber optic    3096
No             1526
Name: tenure, dtype: int64


In [18]:
# using multiple aggregation functions at once
grouped = my_telco_data.groupby('InternetService')
print grouped['tenure'].agg([np.sum, np.mean, np.std])

                    sum       mean        std
InternetService                              
DSL               79461  32.821561  24.812178
Fiber optic      101914  32.917959  24.425332
No                46615  30.547182  24.356507


**References**

https://codeburst.io/getting-started-with-data-analysis-in-python-2aaa4dbedd46

https://community.modeanalytics.com/python/tutorial/defining-python-functions/

https://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/